services:
  pihole:
    container_name: adharbor-pihole
    image: ${PIHOLE_IMAGE}
    hostname: ${PIHOLE_HOSTNAME}
    restart: unless-stopped
    ports:
      - "${PIHOLE_DNS_PORT}:53/tcp"
      - "${PIHOLE_DNS_PORT}:53/udp"
      - "${PIHOLE_WEB_PORT}:80/tcp"
    environment:
      TZ: ${TZ}
      FTLCONF_dns_listeningMode: all
      FTLCONF_dns_upstreams: ${PIHOLE_UPSTREAM_DNS}
      WEBPASSWORD_FILE: /run/secrets/pihole_webpassword
    volumes:
      - ./volumes/etc-pihole:/etc/pihole
    secrets:
      - pihole_webpassword

secrets:
  pihole_webpassword:
    file: ./.secrets/pihole_webpassword.txt
